### ISSUE TITLE
Add new channel for Slack

### ISSUE THREAD

**Issue by ryancurrah** [jaimeteb/chatto#2]
Awesome project. What would it take add a new slack integration?

**Comment by jaimeteb** [comment]
Thank you very much!
I'm new to Slack, so I'm exploring the API and how Bots are typically integrated. The integration would have to be implemented in the [server](https://github.com/jaimeteb/chatto/tree/master/bot/server.go) to receive and send messages, and the configuration loaded from [channels](https://github.com/jaimeteb/chatto/tree/master/bot/channels.go).
I've seen other frameworks do this kind of Slack integration so I might take a look at those, and soon it will be added.
Also, I want to refactor the channels in order to allow for easier and further integrations.

**Comment by ryancurrah** [comment]
I can wait for channels to be refactored then look at adding the Slack integration myself.

**Comment by ryancurrah** [comment]
This would probably be a good library to utilize for this: https://github.com/shomali11/slacker.

**Comment by jaimeteb** [comment]
#4

**Comment by jaimeteb** [comment]
Slack channel integration added in v0.4.0
@ryancurrah thank you for your suggestion.

**Comment by ryancurrah** [comment]
Cool I will give it a try this weekend.
