### ISSUE TITLE
more complicated example?

### ISSUE THREAD

**Issue by jinfagang** [jaimeteb/chatto#5]
A more complicated example, for instance, we want a robot that can solve some basic functions like what's the weather today? Tell me a joke, do u know how is the tallest man in the world, how to combines all these intent into a full example?

**Comment by jaimeteb** [comment]
Hello @jinfagang and thank you for your interest.

I have created a new example, the [Misc Bot](https://chatto.jaimeteb.com/examples/misc/), which does some of the tasks that you requested.

The finite state machine is not very complex, since the actions work mostly as commands, but the interesting aspect is the integration with multiple APIs through the chatto extensions. The extensions in the example are written in Go but you can replace them with [anything you want](https://chatto.jaimeteb.com/extensions/).

Take a look at what this example can do on Telegram by clicking [here](t.me/chatto_misc_bot).

Let me know what you think.

**Comment by jinfagang** [comment]
@jaimeteb That's awesome!

You are so brilliant and quickly showing a dedicated example of it. I have another suggestion: can we make another project which using cahtto as a lib (or directly make a complicated example inside chatto), which can support many languages? On my side I want send you some PR that I want implement in Mandrian.

what I want is to maintian a rich robot that have many basic functions.

**Comment by jinfagang** [comment]
@jaimeteb By the way, do u have a telegram group to talk about this lib? I really hope to learn more about it

**Comment by jaimeteb** [comment]
I am not very familiar with Mandarin but I believe it should behave well with the Naive Bayes classifier, since it treats words as separate features.

I'll do some tests in Mandarin and let you know how it goes!

**Comment by jinfagang** [comment]
@jaimeteb thank u! 其实中文也很简单, 简单易懂易学,哈哈哈哈哈

**Comment by AlexanderMatveev** [comment]
Looks like bot is down

**Comment by jaimeteb** [comment]
> Looks like bot is down

Oh yes, sorry, I took it down. I have another working demo on Telegram, please feel free to check it out:

@chatto_demo_trivia_bot
